### ISSUE TITLE
remove friend issue

### ISSUE THREAD

**Issue by mmmmeng3** [numbers1311407/mongoose-friends#8]
```
`User.removeFriend(req.body.user2, req.body.user1, function(friend,cb){
    	
    	console.log(cb);

    	res.end("friend deleted!");
    });`
```

is not working . get friend deleted from response , but on mongodb side`
``result: { ok: 1, nModified: 0, n: 0 }`` `nothing changed

**Comment by SamuelDuke** [comment]
I am having the same issue.

exports.deleteFriends = (req, res, next) => {
    const user = req.user._id;
    const friend = req.params.friendID;

    User.removeFriend(user, friend, function (err, friends) {
        if (err) return next(err);

        res.json(friends);
    })
};

[
    {
        "ok": 1,
        "nModified": 0,
        "n": 1
    },
    {
        "ok": 1,
        "nModified": 0,
        "n": 0
    }
]

**Comment by SamuelDuke** [comment]
I had this problem also, and I found that you need to use the actual document, not just the sting _id.

`exports.deleteFriends = (req, res, next) => {
    User.find({$or: [{'_id': req.user._id}, {'_id': req.params.friendID}]}).exec()
        .then(function (users) {
            User.removeFriend(users[0], users[1], function (err, friends) {
                    if (err) return next(err);
                    res.json(friends);
            })
        }
    )
};`

**Comment by numbers1311407** [comment]
@SamuelDuke is correct, but you also could have passed an objectId.

The issue you're having happens because mongo is `$pull`-ing the friend from the array by _id, and the native mongo behavior doesn't cast strings to ObjectIds.

This actually isn't a bug.  When I first looked at it just now I thought automatic casting to ObjectId would be a nice feature and pushed a new version right away.... then immediately realized that was a mistake and reverted it.

This is because while in most cases, casting strings to ObjectIds would be fine, it also *assumes the ids of your models are ObjectIds when they may not be*.  It may be a worthwhile feature to examine strings and only attempt to cast them into ObjectIds if they match the appropriate pattern, but for now I think it's fine as is.

You should add/get/remove friends by passing the actual mongoose model instance or it's _id, or in the case of string arguments, those should be transformed to ObjectIds first.  For example:

    var ObjectId = require('mongoose').Types.ObjectId;
    var user1Id = new ObjectId(req.body.user1);
    var user2Id = new ObjectId(req.body.user2);

    User.removeFriend(user1Id, user2Id, function(...);
